default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: todo_ruby
test:
  <<: *default
  database: todo_ruby

production:
  <<: *default
  database: todo_ruby